# Generated by Django 5.1.13 on 2025-10-13 08:05

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("knowledge", "0001_enable_vector"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ko_type",
                    models.CharField(
                        choices=[
                            ("podnet", "Podnet"),
                            ("vyrocna", "Výročná správa"),
                            ("list", "List"),
                            ("tema", "Tématický súhrn"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=300)),
                ("confidence", models.FloatField(default=0.0)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RawFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=300)),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ko",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_files",
                        to="knowledge.knowledgeobject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordinal", models.IntegerField()),
                ("text", models.TextField()),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(dimensions=384, null=True),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "ko",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="knowledge.knowledgeobject",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ko", "ordinal"], name="knowledge_c_ko_id_a117e6_idx"
                    )
                ],
            },
        ),
    ]
